config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers, :activities
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :show, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :joinposts,           only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  attr_accessor :minutes, :hours, :date
  belongs_to :user
  has_many :joiner_relationships, class_name: "Joinpost",
                                  foreign_key: :post_id,
                                  dependent: :destroy
  has_many :joiners, through: :joiner_relationships
  default_scope -> { order(meeting_time: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, length: { maximum: 140 }
  validate  :picture_size
  validates :restaurant_name, presence: true
  validates :meeting_location, presence: true
  #validates :users_attending, presence: true
  validates :meeting_time, presence: true
  validate  :meeting_time_not_past
  validates :date, presence: true
  validates :minutes, presence: true
  validates :hours, presence: true

  private

    def meeting_time_not_past
      if meeting_time < Time.now
        errors.add(:meeting_time, "should not be in the past")
      end
    end

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    @micropost.users_attending = 1 #temporary 
    d = Date.parse(@micropost.date)
    t = Time.parse(@micropost.hours + ":" + @micropost.minutes)
    zone = Time.now.in_time_zone('Pacific Time (US & Canada)').zone
    @micropost.meeting_time = DateTime.new(d.year, d.month, d.day, t.hour, t.min, t.sec, zone)
    if @micropost.save
      current_user.join(@micropost)
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def show 
    @micropost = Micropost.find(params[:id])
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private

    def micropost_params
      params.require(:micropost).permit(:restaurant_name, :meeting_time, :max_spots,
                                        :meeting_location, :content, :picture, 
                                        :hours, :minutes, :date)
    end
    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_join.html.erb
<%= form_for(current_user.activity_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :post_id, @micropost.id %></div>
  <%= f.submit "Join", type="button" class: "btn btn-primary" %>
<% end %>

app/views/microposts/_join_form.html.erb
<% if current_user.joined?(@micropost) %>
  <%= render 'microposts/unjoin' %>
<% else %>
  <%= render 'microposts/join' %>
<% end %>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>" style="float: left; padding-right: 10px">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title"><%= micropost.restaurant_name %></h3>
    </div>
    <div class="panel-body">
      <span class="user" style="font-size: 115%">
        Organizer: <%= link_to micropost.user.name, micropost.user %>
      </span>
      <div class="location">
        Meeting at: <%= micropost.meeting_location %>
      </div>
      <div class="meeting_time">
        At: <%= micropost.meeting_time.strftime('%Y-%m-%d %H:%M:%S %Z') %>
      </div>
      <div class="participants">
        <% if micropost.max_spots.nil? %>
          Participants: <%= micropost.joiners.count %>
        <% else %>
          Participants: <%= micropost.joiners.count %>/<%= micropost.max_spots %>
        <% end %>
      </div>
      <div class="content">
        <%= micropost.content %>
        <%= image_tag micropost.picture.url if micropost.picture? %>
      </div>
      <div class="join_activity", style="padding-top: 10px">
        <% if current_user.joined?(micropost) %>
          <%= link_to "Unjoin", joinpost_path(id: micropost.id), method: :delete %>
        <% else %>
          <%= link_to "Join", joinposts_path(post_id: micropost.id), method: :post %>
        <% end %>
      </div>
      <span class="joiners_list">
          <% if micropost.joiners.length == 1 %>
            <% micropost.joiners.each do |u| %>
            <span><%= u.name.split.first%></span>
            <% end %>
          <% else %> 
            <span> <%= micropost.joiners.map{|u| u.name}.join(", ") %> </span>
          <% end %>  
      </span>
      
      <span class="timestamp">
        Posted <%= time_ago_in_words(micropost.created_at) %> ago.
        <% if current_user?(micropost.user) %>
          <%= link_to "delete", micropost, method: :delete,
                                           data: { confirm: "Are you sure?" } %>
        <% end %>
      </span>
    </div>
  </div>
</li>

app/views/microposts/_unjoin.html.erb
<%= form_for(current_user.activity_relationships.find_by(post_id: @micropost.id),
             html: {method: :delete},
             remote: true) do |f| %>
  <%= f.submit "Unjoin", class: "btn" %>
<% end %>

app/views/microposts/show.html.erb
<% provide(:title, "Meet at " + @micropost.restaurant_name) %>
<div class="row">
  <div class="meetup_info">
    <span id="user"><%= link_to @micropost.user.name, @micropost.user %></span>
    <span id="restaurant_name">
      <%= @micropost.restaurant_name %>
    </span>
    <span id="location">
      <%= @micropost.meeting_location %>
    </span>
    <span id="meeting_time">
      <%= @micropost.meeting_time.strftime('%m-%d-%Y %H:%M:%S %Z') %>
    </span>
    <span id="max_spots">
      Max spots: <%= @micropost.max_spots %>
    </span>
    <span id="users_attending">
      Users coming: <%= @micropost.users_attending %>
    </span>
    <span id="content">
      <%= @micropost.content %>
      <%= image_tag @micropost.picture.url if @micropost.picture? %>
    </span>
    <span id="timestamp">
      Posted <%= time_ago_in_words(@micropost.created_at) %> ago.
      <% if current_user?(@micropost.user) %>
        <%= link_to "delete", @micropost, method: :delete,
                                         data: { confirm: "You sure?" } %>
      <% end %>
    </span>
    <div id="joiners">
      <% if @micropost.joiners.any? %>
        <%= @micropost.joiners %>
      <% end %>
    </div>
    <div id="join_activity">
      <%= render 'microposts/join_form' %>
    </div>
  </div>
</div>